version: '3.8'

services:
  nginx:
    networks:
      - local_network
    image: nginx:latest
    container_name: nginx_static_server
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  mysql:
    networks:
      - local_network
    image: mysql:8
    container_name: ceos_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ceos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      interval: 3s
      retries: 10

  ceos-api:
    container_name: ceos-api
    build: .
    image: ceos-api
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - local_network
    volumes:
      - .:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy

  olgtm:
    networks:
      - local_network
    image: grafana/otel-lgtm
    ports:
      - 3005:3000
      - 9090:9090
      - 4318:4318
      - 4317:4317

networks:
  local_network:
volumes:
  mysql_data:
