version: '3.8'

services:
  nginx:
    networks:
      - local_network
    image: nginx:latest
    container_name: nginx_static_server
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"

  mysql:
    networks:
      - local_network
    image: mysql:8
    container_name: ceos_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ceos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 3s
      interval: 3s
      retries: 10

  ceos-api:
    container_name: ceos-api
    build: .
    image: ceos-api
    command: npm run start:dev
    ports:
      - 3000:3000
    networks:
      - local_network
    volumes:
      - .:/usr/src/app
    depends_on:
      mysql:
        condition: service_healthy

  jaeger:
    networks:
      - local_network
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "8081:16686"  # Jaeger UI
      - "14268"
      - "14250"

  otel-collector:
    networks:
      - local_network
    image: otel/opentelemetry-collector:latest
    container_name: ceos_otel-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "1888:1888"   # pprof extension
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # http gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
    links:
      - jaeger

networks:
  local_network:
volumes:
  mysql_data:
